apiVersion : apps/v1
kind: Deployment
metadata:
  name: angulardemosat
  labels:
    app: angulardemosat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angulardemosat
  template:
    metadata:
      labels:
        app: angulardemosat 
    spec:
      containers:
        - name: angulardemosat 
          image: jccontainerreg.azurecr.io/angulardemosat
          ports:
          - containerPort: 80
