apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: fridayangularimage 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fridayangularimage 
    spec:
      containers:
        - name: fridayangularimage 
          image: jccontainerreg.azurecr.io/fridayangularimage
          ports:
          - containerPort: 80